version: "3.7"
services:
  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=password
  web:
    image: web:latest
    ports:
      - "3000:3000"
    depends_on:
      - db